namespace Quark.Tests;

public class ActorVersionRegistryTests
{
    [Fact]
    public void ActorVersionRegistry_ExistsInGenerated()
    {
        // The ActorVersionRegistry should be generated by AssemblyVersionSourceGenerator
        // It should exist in the Quark.Generated namespace
        
        // Access the generated registry
        var versionMap = Quark.Generated.ActorVersionRegistry.VersionMap;
        
        // Should not be null
        Assert.NotNull(versionMap);
        
        // Should contain actor types from the test assembly
        // (assuming we have actors in the test assembly)
    }
    
    [Fact]
    public void ActorVersionRegistry_GetVersion_ReturnsVersionForActorType()
    {
        // Arrange - we should have some actor types in this test assembly
        var actorTypes = Quark.Generated.ActorVersionRegistry.GetAllActorTypes();
        
        // Act & Assert
        foreach (var actorType in actorTypes)
        {
            var version = Quark.Generated.ActorVersionRegistry.GetVersion(actorType);
            Assert.NotNull(version);
            Assert.False(string.IsNullOrEmpty(version.Version));
        }
    }
    
    [Fact]
    public void ActorVersionRegistry_GetVersion_NonExistentActor_ReturnsNull()
    {
        // Act
        var version = Quark.Generated.ActorVersionRegistry.GetVersion("NonExistentActor");
        
        // Assert
        Assert.Null(version);
    }
    
    [Fact]
    public void ActorVersionRegistry_GetAllActorTypes_ReturnsCollection()
    {
        // Act
        var actorTypes = Quark.Generated.ActorVersionRegistry.GetAllActorTypes();
        
        // Assert
        Assert.NotNull(actorTypes);
        // The test assembly should have some actor types
        Assert.NotEmpty(actorTypes);
    }
}
