using Quark.Abstractions;

namespace Quark.Client;

/// <summary>
/// Partial static class that will be extended by the ProxySourceGenerator
/// to include CreateProxy&lt;TActorInterface&gt;(IClusterClient, string) method.
/// </summary>
/// <remarks>
/// The ProxySourceGenerator generates the CreateProxy method at compile-time
/// for each interface inheriting from IQuarkActor or registered via QuarkActorContext.
/// This enables AOT-compatible, type-safe actor proxies with zero reflection.
/// </remarks>
internal static class ActorProxyFactory
{
    /// <summary>
    /// Registry of actor interface types to their corresponding proxy factory functions.
    /// </summary>
    private static readonly Dictionary<Type, Func<IQuarkActor>> ActorFac = new Dictionary<Type, Func<IQuarkActor>>();

    // The CreateProxy<TActorInterface>(IClusterClient client, string actorId) method
    // will be generated by ProxySourceGenerator in ActorProxyFactory.g.cs

    /// <summary>
    /// Creates a type-safe actor proxy for the specified actor interface and ID.
    /// </summary>
    /// <param name="client"></param>
    /// <param name="actorId"></param>
    /// <typeparam name="TActorProxy"></typeparam>
    /// <returns></returns>
    /// <exception cref="ArgumentNullException"></exception>
    /// <exception cref="ArgumentException"></exception>
    /// <exception cref="InvalidOperationException"></exception>
    public static TActorProxy CreateProxy<TActorProxy>(IClusterClient client, string actorId)
        where TActorProxy : IQuarkActor
    {
        if (client == null)
        {
            throw new ArgumentNullException(nameof(client));
        }

        if (string.IsNullOrWhiteSpace(actorId))
        {
            throw new ArgumentException("Actor ID cannot be null or whitespace.", nameof(actorId));
        }

        if (ActorFac.TryGetValue(typeof(TActorProxy), out var factory))
        {
            return (TActorProxy)factory();
        }

        throw new InvalidOperationException(
            $"No proxy factory registered for actor interface type {typeof(TActorProxy).FullName}.");
    }

    public static void RegisterProxyFactory<TActorProxy>(Func<IQuarkActor> factory) where TActorProxy : IQuarkActor
    {
        ActorFac[typeof(TActorProxy)] = factory;
    }
}