using System.Collections.Concurrent;
using Microsoft.Extensions.DependencyInjection;
using Quark.Abstractions;

namespace Quark.Client;

/// <summary>
/// Factory for creating type-safe actor proxies.
/// The actual implementation is generated at compile-time by the ProxySourceGenerator.
/// </summary>
internal sealed class ActorProxyFactory : IActorFactory
{
    private readonly ConcurrentDictionary<(Type, string), IActor> _actors = new();
    private readonly IServiceProvider? _serviceProvider;
    
    public ActorProxyFactory(IServiceProvider? serviceProvider = null)
    {
        _serviceProvider = serviceProvider;
    }
    
    public TActor CreateActor<TActor>(string actorId) where TActor : IActor
    {
        if (string.IsNullOrWhiteSpace(actorId))
            throw new ArgumentException("Actor ID cannot be null or whitespace.", nameof(actorId));

        // Create a new service scope for this actor instance
        IServiceScope? serviceScope = null;
        if (_serviceProvider != null) serviceScope = _serviceProvider.CreateScope();

        // Call the source-generated factory method
        // This will be generated by the ProxySourceGenerator
        var actor = ActorProxyFactoryRegistry.CreateActor<TActor>(actorId, this, serviceScope);

        return actor;
    }

    public TActor GetOrCreateActor<TActor>(string actorId) where TActor : IActor
    {
        var key = (typeof(TActor), actorId);
        return (TActor)_actors.GetOrAdd(key, _ => CreateActor<TActor>(actorId));
    }
}


/// <summary>
///     Registry for actor factory methods.
///     This class is populated by source generators.
/// </summary>
public static class ActorProxyFactoryRegistry
{
    private static readonly Dictionary<Type, Func<string, IActorFactory?, IServiceScope?, IActor>> Factories = new();

    /// <summary>
    ///     Registers an actor factory method.
    /// </summary>
    public static void RegisterFactory<TActor>(Func<string, IActorFactory?, IServiceScope?, TActor> factory)
        where TActor : IActor
    {
        Factories[typeof(TActor)] = (id, f, s) => factory(id, f, s);
    }

    /// <summary>
    ///     Creates an actor using the registered factory method.
    /// </summary>
    public static TActor CreateActor<TActor>(string actorId, IActorFactory? actorFactory, IServiceScope? serviceScope)
        where TActor : IActor
    {
        var actorType = typeof(TActor);

        if (Factories.TryGetValue(actorType, out var factory))
            return (TActor)factory(actorId, actorFactory, serviceScope);

        throw new InvalidOperationException(
            $"No factory registered for actor type {actorType.Name}. " +
            "Ensure the actor is marked with [Actor] attribute for source generation.");
    }
}