using Quark.Abstractions;

namespace Quark.Client;

/// <summary>
/// Partial static class that will be extended by the ProxySourceGenerator
/// to include CreateProxy&lt;TActorInterface&gt;(IClusterClient, string) method.
/// </summary>
/// <remarks>
/// The ProxySourceGenerator generates the CreateProxy method at compile-time
/// for each interface inheriting from IQuarkActor or registered via QuarkActorContext.
/// This enables AOT-compatible, type-safe actor proxies with zero reflection.
/// </remarks>
internal static partial class ActorProxyFactory
{
    // The CreateProxy<TActorInterface>(IClusterClient client, string actorId) method
    // will be generated by ProxySourceGenerator in ActorProxyFactory.g.cs
}