using Bank.Grains;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Quark.Client;
using Quark.Core;
using Quark.Core.Abstractions.Hosting;
using Quark.Persistence.Abstractions.Journaling;
using Quark.Persistence.InMemory;
using Quark.Runtime;
using Quark.Transport.Tcp;

IHost host = Host.CreateDefaultBuilder(args)
    .UseQuark(silo =>
    {
        silo.Services.AddQuarkRuntime();
        silo.Services.AddTcpTransport();
        silo.UseLocalhostClustering(gatewayPort: 30005);

        // --- Storage providers ------------------------------------------------
        // Default IGrainStorage — backs IPersistentActivationMemory<T> (accounts) and
        // the [PersistentState("profile")] slot. Swap this single line for
        // AddRedisGrainStorage(o => o.ConnectionString = "localhost:6379") to go durable.
        silo.Services.AddInMemoryGrainStorage();

        // Event log — backs the JournaledGrain ledger.
        silo.Services.AddSingleton<ILogStorage, InMemoryLogStorage>();

        // Deep copiers for the storage-backed state types ([GenerateSerializer]).
        silo.Services.AddBankStateCopiers();

        // DI service resolved inside the vault's eager-memory factory.
        silo.Services.AddSingleton<IInterestRateService, InterestRateService>();

        // --- Grains -----------------------------------------------------------
        // Generated by BehaviorRegistrationGenerator: registers all three behaviors,
        // their transport dispatchers, and the IActivationMemory / IPersistentActivationMemory /
        // IPersistentState accessors — including the JournaledGrain's activation memory.
        silo.Services.AddBankGrainsBehaviors();
    })
    .UseQuarkClient(client =>
    {
        client.Services.AddLocalClusterClient();
        // Generated by ClientProxyRegistrationGenerator in Bank.GrainInterfaces.
        client.Services.AddBankGrainInterfacesGrainProxies();
    })
    .Build();

await host.StartAsync();
Console.WriteLine("Bank persistence sample — silo ready on port 30005. Press Ctrl+C to stop.");
await host.WaitForShutdownAsync();
