using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Microsoft.Extensions.Logging;
using Quark.Abstractions.Migration;
using Quark.Core.Actors.Migration;

namespace Quark.Extensions.DependencyInjection;

/// <summary>
/// Extension methods for registering Phase 10.1.1 (Zero Downtime & Rolling Upgrades) services.
/// </summary>
public static class ZeroDowntimeExtensions
{
    /// <summary>
    /// Adds actor activity tracking for hot/cold detection during migration.
    /// This is required for live actor migration to prioritize cold actors.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddActorActivityTracking(this IServiceCollection services)
    {
        services.TryAddSingleton<IActorActivityTracker, ActorActivityTracker>();
        return services;
    }

    /// <summary>
    /// Adds actor migration coordination for live actor migration during rolling upgrades.
    /// Requires state persistence and optionally reminder table for full functionality.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddActorMigration(this IServiceCollection services)
    {
        services.TryAddSingleton<IActorMigrationCoordinator, ActorMigrationCoordinator>();
        
        // Also add activity tracking if not already registered
        services.AddActorActivityTracking();
        
        return services;
    }

    /// <summary>
    /// Adds version tracking and compatibility checking for version-aware placement.
    /// Enables silos to track actor assembly versions and prefer compatible versions during placement.
    /// If cluster membership is available, uses cluster-synchronized version tracking.
    /// Otherwise, uses local-only version tracking.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddVersionAwarePlacement(this IServiceCollection services)
    {
        // Register version tracker with factory that chooses between local and cluster-aware implementations
        services.TryAddSingleton<IVersionTracker>(sp =>
        {
            var clusterMembership = sp.GetService<Quark.Abstractions.Clustering.IClusterMembership>();
            
            if (clusterMembership != null)
            {
                // Cluster membership is available - use cluster-synchronized version tracking
                var clusterLogger = sp.GetRequiredService<ILogger<ClusterVersionTracker>>();
                return new ClusterVersionTracker(clusterLogger, clusterMembership);
            }
            else
            {
                // No cluster membership - use local-only version tracking
                var localLogger = sp.GetRequiredService<ILogger<VersionTracker>>();
                return new VersionTracker(localLogger);
            }
        });
        
        services.TryAddSingleton<IVersionCompatibilityChecker, VersionCompatibilityChecker>();
        return services;
    }
    
    /// <summary>
    /// Registers the actor versions from the application assembly into the version tracker.
    /// This method should be called after AddVersionAwarePlacement() and requires the ActorVersionRegistry
    /// to be generated by the AssemblyVersionSourceGenerator in your application assembly.
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <param name="versionMap">The version map from Quark.Generated.ActorVersionRegistry.VersionMap</param>
    /// <returns>The service collection for chaining.</returns>
    /// <example>
    /// <code>
    /// services.AddVersionAwarePlacement();
    /// services.RegisterActorVersions(Quark.Generated.ActorVersionRegistry.VersionMap);
    /// </code>
    /// </example>
    public static IServiceCollection RegisterActorVersions(
        this IServiceCollection services,
        IReadOnlyDictionary<string, AssemblyVersionInfo> versionMap)
    {
        if (versionMap == null)
        {
            throw new ArgumentNullException(nameof(versionMap));
        }
        
        // Register a hosted service that will register the versions on startup
        services.AddHostedService(sp =>
        {
            var versionTracker = sp.GetRequiredService<IVersionTracker>();
            var logger = sp.GetRequiredService<ILogger<VersionManualRegistrationService>>();
            return new VersionManualRegistrationService(versionTracker, versionMap, logger);
        });
        
        return services;
    }

    /// <summary>
    /// Adds all Phase 10.1.1 (Zero Downtime & Rolling Upgrades) services.
    /// This is a convenience method that registers:
    /// - Actor activity tracking (hot/cold detection)
    /// - Actor migration coordination
    /// - Version-aware placement
    /// </summary>
    /// <param name="services">The service collection.</param>
    /// <returns>The service collection for chaining.</returns>
    public static IServiceCollection AddZeroDowntimeUpgrades(this IServiceCollection services)
    {
        services.AddActorActivityTracking();
        services.AddActorMigration();
        services.AddVersionAwarePlacement();
        return services;
    }
}
