using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Quark.CodeGenerator;

/// <summary>
///     Generates a per-assembly <c>QuarkClientRegistrations</c> partial class with an
///     <c>Add{AssemblyName}GrainProxies(IServiceCollection)</c> extension method that registers
///     every <see cref="Quark.Core.Abstractions.Grains.IGrain"/> and
///     <see cref="Quark.Core.Abstractions.Grains.IGrainObserver"/> interface declared in the assembly:
///     <list type="bullet">
///         <item><c>AddGrainProxy&lt;TInterface, TProxy&gt;()</c> — for <c>IGrain</c> subtypes</item>
///         <item><c>AddObserverProxy&lt;TInterface, TProxy&gt;()</c> — for <c>IGrainObserver</c> subtypes</item>
///     </list>
///     The proxy class name is derived from the interface name by stripping the leading "I" and appending "Proxy"
///     (e.g. <c>ICounterGrain</c> → <c>CounterGrainProxy</c>), matching <see cref="GrainProxyGenerator"/>'s
///     naming convention. Generation is skipped when <c>Quark.Client</c> is not referenced.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class ClientProxyRegistrationGenerator : IIncrementalGenerator
{
    private const string IGrainFqn = "Quark.Core.Abstractions.Grains.IGrain";
    private const string IGrainObserverFqn = "Quark.Core.Abstractions.Grains.IGrainObserver";
    private const string GuardTypeFqn = "Quark.Client.ClientServiceCollectionExtensions";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValueProvider<string?> assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.AssemblyName);

        // Guard: skip entirely when Quark.Client is not referenced.
        IncrementalValueProvider<bool> hasQuarkClient = context.CompilationProvider
            .Select(static (c, _) => c.GetTypeByMetadataName(GuardTypeFqn) is not null);

        IncrementalValuesProvider<ProxyModel> models = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is InterfaceDeclarationSyntax,
                ExtractModel)
            .Where(static m => m is not null)
            .Select(static (m, _) => m!.Value);

        context.RegisterSourceOutput(
            hasQuarkClient.Combine(assemblyName).Combine(models.Collect()),
            static (ctx, pair) => Emit(ctx, pair.Left.Left, pair.Left.Right, pair.Right));
    }

    // -----------------------------------------------------------------------
    // Model extraction
    // -----------------------------------------------------------------------

    private static ProxyModel? ExtractModel(GeneratorSyntaxContext ctx, CancellationToken ct)
    {
        if (ctx.Node is not InterfaceDeclarationSyntax) return null;
        if (ctx.SemanticModel.GetDeclaredSymbol(ctx.Node, ct) is not INamedTypeSymbol iface) return null;

        bool isGrain = false;
        bool isObserver = false;
        foreach (INamedTypeSymbol parent in iface.AllInterfaces)
        {
            string fqn = parent.ToDisplayString();
            if (fqn == IGrainFqn) isGrain = true;
            else if (fqn == IGrainObserverFqn) isObserver = true;
        }

        if (!isGrain && !isObserver) return null;
        if (isGrain && isObserver) return null; // ambiguous — GrainProxyGenerator skips these too

        string ns = iface.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : iface.ContainingNamespace.ToDisplayString();

        string ifaceFqn = iface.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string proxyName = iface.Name.StartsWith("I", StringComparison.Ordinal) && iface.Name.Length > 1
            ? iface.Name.Substring(1) + "Proxy"
            : iface.Name + "Proxy";

        string proxyFqn = string.IsNullOrEmpty(ns)
            ? $"global::{proxyName}"
            : $"global::{ns}.{proxyName}";

        return new ProxyModel(ifaceFqn, proxyFqn, isObserver);
    }

    // -----------------------------------------------------------------------
    // Code emission
    // -----------------------------------------------------------------------

    private static void Emit(
        SourceProductionContext ctx,
        bool hasQuarkClient,
        string? assemblyName,
        ImmutableArray<ProxyModel> models)
    {
        if (!hasQuarkClient || models.IsDefaultOrEmpty) return;

        string methodName = SanitizeAssemblyName(assemblyName ?? "Unknown");

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Quark.CodeGenerator — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Quark.CodeGenerator\", \"0.1.0\")]");
        sb.AppendLine("public static partial class QuarkClientRegistrations");
        sb.AppendLine("{");
        sb.AppendLine($"    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection {methodName}(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (ProxyModel m in models.OrderBy(static m => m.InterfaceFqn, StringComparer.Ordinal))
        {
            if (m.IsObserver)
            {
                sb.AppendLine($"        global::Quark.Client.ClientServiceCollectionExtensions.AddObserverProxy<{m.InterfaceFqn}, {m.ProxyFqn}>(services);");
            }
            else
            {
                sb.AppendLine($"        global::Quark.Client.ClientServiceCollectionExtensions.AddGrainProxy<{m.InterfaceFqn}, {m.ProxyFqn}>(services);");
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource("QuarkClientRegistrations.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }

    private static string SanitizeAssemblyName(string assemblyName)
    {
        var sb = new StringBuilder("Add");
        bool capitalizeNext = true;
        foreach (char c in assemblyName)
        {
            if (c == '.' || c == '-' || c == '_')
            {
                capitalizeNext = true;
                continue;
            }

            if (char.IsLetterOrDigit(c))
            {
                sb.Append(capitalizeNext ? char.ToUpperInvariant(c) : c);
                capitalizeNext = false;
            }
        }

        sb.Append("GrainProxies");
        return sb.ToString();
    }

    // -----------------------------------------------------------------------
    // Model
    // -----------------------------------------------------------------------

    private readonly struct ProxyModel : IEquatable<ProxyModel>
    {
        public ProxyModel(string interfaceFqn, string proxyFqn, bool isObserver)
        {
            InterfaceFqn = interfaceFqn;
            ProxyFqn = proxyFqn;
            IsObserver = isObserver;
        }

        public string InterfaceFqn { get; }
        public string ProxyFqn { get; }
        public bool IsObserver { get; }

        public bool Equals(ProxyModel other) =>
            InterfaceFqn == other.InterfaceFqn &&
            ProxyFqn == other.ProxyFqn &&
            IsObserver == other.IsObserver;

        public override bool Equals(object? obj) => obj is ProxyModel other && Equals(other);

        public override int GetHashCode()
        {
            unchecked
            {
                int hash = InterfaceFqn.GetHashCode();
                hash = hash * 397 ^ ProxyFqn.GetHashCode();
                hash = hash * 397 ^ IsObserver.GetHashCode();
                return hash;
            }
        }
    }
}
