using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Text;

namespace Quark.CodeGenerator;

/// <summary>
/// Source generator that emits grain proxy classes for every interface that
/// extends <c>IGrain</c>.  The emitted proxy is the AOT-safe replacement for
/// runtime-generated grain references.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class GrainProxyGenerator : IIncrementalGenerator
{
    private const string IGrainFqn = "Quark.Core.Abstractions.IGrain";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<InterfaceDeclarationSyntax> grainInterfaces =
            context.SyntaxProvider.CreateSyntaxProvider(
                predicate: static (node, _) => node is InterfaceDeclarationSyntax,
                transform: FilterGrainInterfaces)
            .Where(static x => x is not null)!;

        context.RegisterSourceOutput(grainInterfaces.Collect(), Emit);
    }

    private static InterfaceDeclarationSyntax? FilterGrainInterfaces(
        GeneratorSyntaxContext ctx, System.Threading.CancellationToken ct)
    {
        var iface = (InterfaceDeclarationSyntax)ctx.Node;
        ISymbol? symbol = ctx.SemanticModel.GetDeclaredSymbol(iface, ct);
        if (symbol is not INamedTypeSymbol namedType)
            return null;

        // Walk all interfaces to see if IGrain is in the hierarchy.
        foreach (INamedTypeSymbol iface2 in namedType.AllInterfaces)
        {
            if (iface2.ToDisplayString() == IGrainFqn)
                return iface;
        }
        return null;
    }

    private static void Emit(
        SourceProductionContext ctx,
        System.Collections.Immutable.ImmutableArray<InterfaceDeclarationSyntax> interfaces)
    {
        foreach (InterfaceDeclarationSyntax iface in interfaces)
        {
            string ifaceName = iface.Identifier.Text;
            string source = BuildProxySource(ifaceName, iface);
            ctx.AddSource($"{ifaceName}.QuarkProxy.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildProxySource(string ifaceName, InterfaceDeclarationSyntax iface)
    {
        // TODO (M2): emit a full grain proxy with method stubs that route through
        //            the Quark messaging infrastructure.
        return $@"// <auto-generated/>
// Generated by Quark.CodeGenerator — Milestone 2 will emit real grain proxy logic.
#nullable enable
// Grain proxy for {ifaceName} will be generated here.
";
    }
}
