using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Quark.CodeGenerator;

/// <summary>
/// Source generator that emits IFieldCodec&lt;T&gt; and IDeepCopier&lt;T&gt; implementations
/// for every type annotated with [GenerateSerializer].
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SerializerGenerator : IIncrementalGenerator
{
    private const string GenerateSerializerAttributeFqn =
        "Quark.Serialization.Abstractions.GenerateSerializerAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<TypeDeclarationSyntax> annotated = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateSerializerAttributeFqn,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: static (ctx, _) => (TypeDeclarationSyntax)ctx.TargetNode);

        context.RegisterSourceOutput(annotated.Collect(), Emit);
    }

    private static void Emit(
        SourceProductionContext ctx,
        System.Collections.Immutable.ImmutableArray<TypeDeclarationSyntax> types)
    {
        foreach (TypeDeclarationSyntax type in types)
        {
            string typeName = type.Identifier.Text;
            string source = BuildCodecSource(typeName, type);
            ctx.AddSource($"{typeName}.QuarkSerializer.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildCodecSource(string typeName, TypeDeclarationSyntax type)
    {
        // TODO (M2): inspect [Id] attributes and emit real read/write field code.
        // This is a placeholder scaffold that compiles and indicates intent.
        return $@"// <auto-generated/>
// Generated by Quark.CodeGenerator — Milestone 2 will emit real codec logic.
#nullable enable
// Codec for {typeName} will be generated here.
";
    }
}
