using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using System.Threading;

namespace Quark.CodeGenerator;

/// <summary>
/// Source generator that emits <c>IFieldCodec&lt;T&gt;</c> and <c>IDeepCopier&lt;T&gt;</c>
/// implementations for every type annotated with <c>[GenerateSerializer]</c>.
///
/// For each serializable member (property/field tagged <c>[Id(N)]</c>) the generator:
/// <list type="bullet">
///   <item>Writes/reads via the codec resolved from <c>ICodecProvider</c>.</item>
///   <item>Uses field-id switch dispatch on deserialisation; skips unknown fields.</item>
/// </list>
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class SerializerGenerator : IIncrementalGenerator
{
    private const string GenerateSerializerFqn =
        "Quark.Serialization.Abstractions.GenerateSerializerAttribute";
    private const string IdAttributeFqn =
        "Quark.Serialization.Abstractions.IdAttribute";

    /// <inheritdoc/>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<TypeModel?> models = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateSerializerFqn,
                predicate: static (node, _) => node is TypeDeclarationSyntax,
                transform: ExtractModel);

        context.RegisterSourceOutput(
            models.Where(static m => m is not null).Collect(),
            static (ctx, items) => Emit(ctx, items!));
    }

    // -----------------------------------------------------------------------
    // Model extraction (runs in incremental pipeline — no Roslyn types stored)
    // -----------------------------------------------------------------------

    private static TypeModel? ExtractModel(
        GeneratorAttributeSyntaxContext ctx,
        CancellationToken ct)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        // Skip generic types for now — future M2 work.
        if (typeSymbol.IsGenericType)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? string.Empty
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var members = new List<MemberModel>();
        foreach (var member in typeSymbol.GetMembers())
        {
            ct.ThrowIfCancellationRequested();
            foreach (var attr in member.GetAttributes())
            {
                if (attr.AttributeClass?.ToDisplayString() != IdAttributeFqn)
                    continue;
                if (attr.ConstructorArguments.Length == 0)
                    continue;

                var idValue = attr.ConstructorArguments[0].Value;
                uint id = idValue is uint u ? u : (uint)(int)idValue!;

                ITypeSymbol memberType;
                bool isProperty;
                if (member is IPropertySymbol prop && !prop.IsStatic && prop.SetMethod is not null)
                {
                    memberType = prop.Type;
                    isProperty = true;
                }
                else if (member is IFieldSymbol field && !field.IsStatic && !field.IsReadOnly)
                {
                    memberType = field.Type;
                    isProperty = false;
                }
                else
                {
                    continue;
                }

                members.Add(new MemberModel(
                    id,
                    member.Name,
                    memberType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                    isProperty));
            }
        }

        if (members.Count == 0)
            return null;

        return new TypeModel(
            ns,
            typeSymbol.Name,
            typeSymbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            members.OrderBy(m => m.Id).ToList(),
            typeSymbol.IsValueType);
    }

    // -----------------------------------------------------------------------
    // Code emission
    // -----------------------------------------------------------------------

    private static void Emit(
        SourceProductionContext ctx,
        ImmutableArray<TypeModel> models)
    {
        foreach (TypeModel model in models)
        {
            string source = BuildCodecSource(model);
            ctx.AddSource(
                $"{model.TypeName}.QuarkSerializer.g.cs",
                SourceText.From(source, Encoding.UTF8));
        }
    }

    private static string BuildCodecSource(TypeModel m)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by Quark.CodeGenerator — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using global::Quark.Serialization.Abstractions;");
        sb.AppendLine();

        bool hasNs = !string.IsNullOrEmpty(m.Namespace);
        if (hasNs)
        {
            sb.AppendLine($"namespace {m.Namespace};");
            sb.AppendLine();
        }

        // ---- IFieldCodec<T> ------------------------------------------------

        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Quark.CodeGenerator\", \"0.1.0\")]");
        sb.AppendLine($"internal sealed class {m.TypeName}Codec");
        sb.AppendLine($"    : global::Quark.Serialization.Abstractions.IFieldCodec<{m.FqTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Quark.Serialization.Abstractions.ICodecProvider _codecs;");
        sb.AppendLine();
        sb.AppendLine($"    public {m.TypeName}Codec(global::Quark.Serialization.Abstractions.ICodecProvider codecs)");
        sb.AppendLine("        => _codecs = codecs;");
        sb.AppendLine();

        // WriteField
        sb.AppendLine($"    public void WriteField(");
        sb.AppendLine($"        global::Quark.Serialization.Abstractions.CodecWriter writer,");
        sb.AppendLine($"        uint fieldId,");
        sb.AppendLine($"        global::System.Type expectedType,");
        sb.AppendLine($"        {m.FqTypeName} value)");
        sb.AppendLine("    {");
        if (!m.IsValueType)
        {
            sb.AppendLine("        if (value is null)");
            sb.AppendLine("        {");
            sb.AppendLine("            writer.WriteFieldHeader(fieldId, global::Quark.Serialization.Abstractions.WireType.Extended);");
            sb.AppendLine("            writer.WriteByte((byte)global::Quark.Serialization.Abstractions.ExtendedWireType.Null);");
            sb.AppendLine("            return;");
            sb.AppendLine("        }");
        }
        sb.AppendLine("        writer.WriteFieldHeader(fieldId, global::Quark.Serialization.Abstractions.WireType.TagDelimited);");
        foreach (MemberModel member in m.Members)
        {
            sb.AppendLine($"        _codecs.GetRequiredCodec<{member.FqTypeName}>().WriteField(writer, {member.Id}u, typeof({member.FqTypeName}), value.{member.Name});");
        }
        sb.AppendLine("        writer.WriteFieldHeader(0u, global::Quark.Serialization.Abstractions.WireType.EndTagDelimited);");
        sb.AppendLine("    }");
        sb.AppendLine();

        // ReadValue
        sb.AppendLine($"    public {m.FqTypeName} ReadValue(");
        sb.AppendLine($"        global::Quark.Serialization.Abstractions.CodecReader reader,");
        sb.AppendLine($"        global::Quark.Serialization.Abstractions.Field field)");
        sb.AppendLine("    {");
        if (!m.IsValueType)
        {
            sb.AppendLine("        if (field.WireType == global::Quark.Serialization.Abstractions.WireType.Extended)");
            sb.AppendLine("        {");
            sb.AppendLine("            return default!;");
            sb.AppendLine("        }");
        }
        sb.AppendLine($"        var result = new {m.FqTypeName}();");
        sb.AppendLine("        global::Quark.Serialization.Abstractions.Field f;");
        sb.AppendLine("        while (!(f = reader.ReadFieldHeader()).IsEndObject)");
        sb.AppendLine("        {");
        sb.AppendLine("            switch ((int)f.FieldId)");
        sb.AppendLine("            {");
        foreach (MemberModel member in m.Members)
        {
            sb.AppendLine($"                case {member.Id}: result.{member.Name} = _codecs.GetRequiredCodec<{member.FqTypeName}>().ReadValue(reader, f); break;");
        }
        sb.AppendLine("                default: SkipField(reader, f); break;");
        sb.AppendLine("            }");
        sb.AppendLine("        }");
        sb.AppendLine("        return result;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // SkipField helper
        sb.AppendLine("    private static void SkipField(");
        sb.AppendLine("        global::Quark.Serialization.Abstractions.CodecReader reader,");
        sb.AppendLine("        global::Quark.Serialization.Abstractions.Field field)");
        sb.AppendLine("    {");
        sb.AppendLine("        switch (field.WireType)");
        sb.AppendLine("        {");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.VarInt:");
        sb.AppendLine("                reader.ReadVarUInt64(); break;");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.Fixed32:");
        sb.AppendLine("                reader.ReadFixed32(); break;");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.Fixed64:");
        sb.AppendLine("                reader.ReadFixed64(); break;");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.LengthPrefixed:");
        sb.AppendLine("                reader.ReadBytes(); break;");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.TagDelimited:");
        sb.AppendLine("                global::Quark.Serialization.Abstractions.Field nested;");
        sb.AppendLine("                while (!(nested = reader.ReadFieldHeader()).IsEndObject)");
        sb.AppendLine("                {");
        sb.AppendLine("                    SkipField(reader, nested);");
        sb.AppendLine("                }");
        sb.AppendLine("                break;");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.Extended:");
        sb.AppendLine("            case global::Quark.Serialization.Abstractions.WireType.EndTagDelimited:");
        sb.AppendLine("                break;");
        sb.AppendLine("        }");
        sb.AppendLine("    }");
        sb.AppendLine("}");
        sb.AppendLine();

        // ---- IDeepCopier<T> ------------------------------------------------
        sb.AppendLine($"[global::System.CodeDom.Compiler.GeneratedCodeAttribute(\"Quark.CodeGenerator\", \"0.1.0\")]");
        sb.AppendLine($"internal sealed class {m.TypeName}Copier");
        sb.AppendLine($"    : global::Quark.Serialization.Abstractions.IDeepCopier<{m.FqTypeName}>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly global::Quark.Serialization.Abstractions.ICopierProvider _copiers;");
        sb.AppendLine();
        sb.AppendLine($"    public {m.TypeName}Copier(global::Quark.Serialization.Abstractions.ICopierProvider copiers)");
        sb.AppendLine("        => _copiers = copiers;");
        sb.AppendLine();
        sb.AppendLine($"    public {m.FqTypeName} DeepCopy({m.FqTypeName} input,");
        sb.AppendLine($"        global::Quark.Serialization.Abstractions.CopyContext context)");
        sb.AppendLine("    {");
        if (!m.IsValueType)
        {
            sb.AppendLine("        if (input is null) return default!;");
            sb.AppendLine($"        var existing = context.TryGetCopy<{m.FqTypeName}>(input);");
            sb.AppendLine("        if (existing is not null) return existing;");
        }
        sb.AppendLine($"        var copy = new {m.FqTypeName}();");
        if (!m.IsValueType)
        {
            sb.AppendLine("        context.RecordCopy(input, copy);");
        }
        foreach (MemberModel member in m.Members)
        {
            sb.AppendLine($"        copy.{member.Name} = _copiers.GetRequiredCopier<{member.FqTypeName}>().DeepCopy(input.{member.Name}, context);");
        }
        sb.AppendLine("        return copy;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    // -----------------------------------------------------------------------
    // Data models (no Roslyn references — safe to cache across incremental steps)
    // -----------------------------------------------------------------------

    private sealed class TypeModel(
        string @namespace,
        string typeName,
        string fqTypeName,
        IReadOnlyList<MemberModel> members,
        bool isValueType)
    {
        public string Namespace { get; } = @namespace;
        public string TypeName { get; } = typeName;
        public string FqTypeName { get; } = fqTypeName;
        public IReadOnlyList<MemberModel> Members { get; } = members;
        public bool IsValueType { get; } = isValueType;
    }

    private sealed class MemberModel(uint id, string name, string fqTypeName, bool isProperty)
    {
        public uint Id { get; } = id;
        public string Name { get; } = name;
        public string FqTypeName { get; } = fqTypeName;
        public bool IsProperty { get; } = isProperty;
    }
}

