using System.Collections.Concurrent;
using Microsoft.Extensions.DependencyInjection;
using Quark.Abstractions;

namespace Quark.Core.Actors;

/// <summary>
///     Default implementation of the actor factory with DI and source generation support.
///     This class uses compile-time code generation - NO REFLECTION.
/// </summary>
public sealed class ActorFactory : IActorFactory
{
    private readonly ConcurrentDictionary<(Type, string), IActor> _actors = new();
    private readonly IServiceProvider? _serviceProvider;

    /// <summary>
    ///     Initializes a new instance of the <see cref="ActorFactory" /> class.
    /// </summary>
    /// <param name="serviceProvider">Optional service provider for dependency injection.</param>
    public ActorFactory(IServiceProvider? serviceProvider = null)
    {
        _serviceProvider = serviceProvider;
    }

    /// <inheritdoc />
    public TActor CreateActor<TActor>(string actorId) where TActor : IActor
    {
        if (string.IsNullOrWhiteSpace(actorId))
            throw new ArgumentException("Actor ID cannot be null or whitespace.", nameof(actorId));

        // Create a new service scope for this actor instance
        IServiceScope? serviceScope = null;
        if (_serviceProvider != null) serviceScope = _serviceProvider.CreateScope();

        // Call the source-generated factory method
        // This will be generated by the ActorSourceGenerator
        var actor = ActorFactoryRegistry.CreateActor<TActor>(actorId, this, serviceScope);

        return actor;
    }

    /// <inheritdoc />
    public TActor GetOrCreateActor<TActor>(string actorId) where TActor : IActor
    {
        var key = (typeof(TActor), actorId);
        return (TActor)_actors.GetOrAdd(key, _ => CreateActor<TActor>(actorId));
    }

    /// <summary>
    ///     Gets an existing actor or creates a new one if it doesn't exist (non-generic version for runtime dispatch).
    /// </summary>
    /// <param name="actorTypeName">The actor type name (from QuarkEnvelope).</param>
    /// <param name="actorId">The unique identifier for the actor.</param>
    /// <returns>The actor instance.</returns>
    public IActor GetOrCreateActorByName(string actorTypeName, string actorId)
    {
        // Look up the Type from the type name
        var actorType = ActorFactoryRegistry.GetActorType(actorTypeName);
        if (actorType == null)
        {
            throw new InvalidOperationException(
                $"No actor type registered with name '{actorTypeName}'. " +
                "Ensure the actor is marked with [Actor] attribute.");
        }

        var key = (actorType, actorId);
        return _actors.GetOrAdd(key, _ =>
        {
            // Create a new service scope for this actor instance
            IServiceScope? serviceScope = null;
            if (_serviceProvider != null)
                serviceScope = _serviceProvider.CreateScope();

            // Call the factory method via the registry
            return ActorFactoryRegistry.CreateActorByName(actorTypeName, actorId, this, serviceScope);
        });
    }
}