using System.Collections.Concurrent;
using Quark.Abstractions;
using Microsoft.Extensions.DependencyInjection;

namespace Quark.Core.Actors;

/// <summary>
/// Default implementation of the actor factory with DI and source generation support.
/// This class uses compile-time code generation - NO REFLECTION.
/// </summary>
public sealed class ActorFactory : IActorFactory
{
    private readonly ConcurrentDictionary<(Type, string), IActor> _actors = new();
    private readonly IServiceProvider? _serviceProvider;

    /// <summary>
    /// Initializes a new instance of the <see cref="ActorFactory"/> class.
    /// </summary>
    /// <param name="serviceProvider">Optional service provider for dependency injection.</param>
    public ActorFactory(IServiceProvider? serviceProvider = null)
    {
        _serviceProvider = serviceProvider;
    }

    /// <inheritdoc />
    public TActor CreateActor<TActor>(string actorId) where TActor : IActor
    {
        if (string.IsNullOrWhiteSpace(actorId))
        {
            throw new ArgumentException("Actor ID cannot be null or whitespace.", nameof(actorId));
        }

        // Create a new service scope for this actor instance
        IServiceScope? serviceScope = null;
        if (_serviceProvider != null)
        {
            serviceScope = _serviceProvider.CreateScope();
        }

        // Call the source-generated factory method
        // This will be generated by the ActorSourceGenerator
        var actor = ActorFactoryRegistry.CreateActor<TActor>(actorId, this, serviceScope);
        
        return actor;
    }

    /// <inheritdoc />
    public TActor GetOrCreateActor<TActor>(string actorId) where TActor : IActor
    {
        var key = (typeof(TActor), actorId);
        return (TActor)_actors.GetOrAdd(key, _ => CreateActor<TActor>(actorId));
    }
}

/// <summary>
/// Registry for actor factory methods.
/// This class is populated by source generators.
/// </summary>
public static partial class ActorFactoryRegistry
{
    private static readonly Dictionary<Type, Func<string, IActorFactory?, IServiceScope?, IActor>> _factories = new();

    /// <summary>
    /// Registers an actor factory method.
    /// </summary>
    public static void RegisterFactory<TActor>(Func<string, IActorFactory?, IServiceScope?, TActor> factory)
        where TActor : IActor
    {
        _factories[typeof(TActor)] = (id, f, s) => factory(id, f, s);
    }

    /// <summary>
    /// Creates an actor using the registered factory method.
    /// </summary>
    public static TActor CreateActor<TActor>(string actorId, IActorFactory? actorFactory, IServiceScope? serviceScope)
        where TActor : IActor
    {
        var actorType = typeof(TActor);
        
        if (_factories.TryGetValue(actorType, out var factory))
        {
            return (TActor)factory(actorId, actorFactory, serviceScope);
        }

        throw new InvalidOperationException(
            $"No factory registered for actor type {actorType.Name}. " +
            "Ensure the actor is marked with [Actor] attribute for source generation.");
    }
}
