// Copyright (c) Quark Framework. All rights reserved.

namespace Quark.Abstractions;

/// <summary>
/// AOT-safe dispatcher interface for invoking actor methods without reflection.
/// Generated by ActorSourceGenerator for each actor type to enable compile-time code generation.
/// </summary>
public interface IActorMethodDispatcher
{
    /// <summary>
    /// Gets the actor type that this dispatcher handles.
    /// </summary>
    Type ActorType { get; }

    /// <summary>
    /// Invokes a method on an actor instance.
    /// </summary>
    /// <param name="actor">The actor instance to invoke the method on.</param>
    /// <param name="methodName">The name of the method to invoke.</param>
    /// <param name="payload">The serialized payload containing method arguments.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>A task containing the serialized result of the method invocation.</returns>
    Task<byte[]> InvokeAsync(
        IActor actor,
        string methodName,
        byte[] payload,
        CancellationToken cancellationToken);
}
