using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Quark.Generators;

/// <summary>
///     Source generator for automatic assembly version detection.
///     Generates a FrozenDictionary mapping actor types to their assembly versions.
///     Part of Phase 10.1.1 (Zero Downtime & Rolling Upgrades).
/// </summary>
[Generator]
public class AssemblyVersionSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with the Actor attribute
        var actorClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsSyntaxTargetForGeneration(s),
                static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Collect all actor classes and combine with compilation
        var compilation = context.CompilationProvider.Combine(actorClasses.Collect());

        // Generate code for all actors at once
        context.RegisterSourceOutput(compilation,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration
               && classDeclaration.AttributeLists.Count > 0;
    }

    private static ClassDeclarationSyntax? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;

        foreach (var attributeList in classDeclaration.AttributeLists)
        foreach (var attribute in attributeList.Attributes)
        {
            var symbolInfo = context.SemanticModel.GetSymbolInfo(attribute);
            if (symbolInfo.Symbol is not IMethodSymbol attributeSymbol)
                continue;

            var attributeType = attributeSymbol.ContainingType;
            var fullName = attributeType.ToDisplayString();

            if (fullName == "Quark.Abstractions.ActorAttribute") return classDeclaration;
        }

        return null;
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<ClassDeclarationSyntax?> actorClasses,
        SourceProductionContext context)
    {
        if (actorClasses.IsEmpty)
            return;

        // Get assembly version from compilation
        var assemblyVersion = GetAssemblyVersion(compilation);
        var assemblyName = compilation.AssemblyName ?? "Unknown";

        var versionEntries = new StringBuilder();
        var hasEntries = false;

        foreach (var classDeclaration in actorClasses)
        {
            if (classDeclaration is null)
                continue;

            var semanticModel = compilation.GetSemanticModel(classDeclaration.SyntaxTree);
            var classSymbol = semanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;

            if (classSymbol is null)
                continue;

            var className = classSymbol.Name;

            // Add entry to the dictionary
            if (hasEntries)
                versionEntries.Append(",\n");

            versionEntries.Append(
                $"            [\"{className}\"] = new AssemblyVersionInfo(\"{assemblyVersion}\", \"{assemblyName}\")");
            hasEntries = true;
        }

        // Only generate if we have actor types
        if (!hasEntries)
            return;

        var source = $$"""
                       // <auto-generated/>
                       #nullable enable
                       using System.Collections.Frozen;
                       using System.Runtime.CompilerServices;
                       using Quark.Abstractions.Migration;
                       
                       namespace Quark.Generated
                       {
                           /// <summary>
                           /// Auto-generated assembly version registry for actor types.
                           /// Generated at compile-time by AssemblyVersionSourceGenerator.
                           /// </summary>
                           public static class ActorVersionRegistry
                           {
                               private static FrozenDictionary<string, AssemblyVersionInfo>? _versionMap;
                       
                               /// <summary>
                               /// Gets the frozen dictionary mapping actor type names to their assembly versions.
                               /// This is populated at compile-time and includes all actor types in this assembly.
                               /// </summary>
                               public static FrozenDictionary<string, AssemblyVersionInfo> VersionMap
                               {
                                   get
                                   {
                                       if (_versionMap == null)
                                       {
                                           _versionMap = new Dictionary<string, AssemblyVersionInfo>
                                           {
                       {{versionEntries}}
                                           }.ToFrozenDictionary();
                                       }
                                       return _versionMap;
                                   }
                               }
                       
                               /// <summary>
                               /// Gets the version information for a specific actor type.
                               /// </summary>
                               /// <param name="actorType">The actor type name.</param>
                               /// <returns>The assembly version info, or null if not found.</returns>
                               public static AssemblyVersionInfo? GetVersion(string actorType)
                               {
                                   return VersionMap.TryGetValue(actorType, out var version) ? version : null;
                               }
                       
                               /// <summary>
                               /// Gets all actor type names registered in this assembly.
                               /// </summary>
                               public static IReadOnlyCollection<string> GetAllActorTypes()
                               {
                                   return VersionMap.Keys;
                               }
                           }
                       }
                       """;

        context.AddSource("ActorVersionRegistry.g.cs", SourceText.From(source, Encoding.UTF8));
    }

    private static string GetAssemblyVersion(Compilation compilation)
    {
        // Try to get version from AssemblyVersionAttribute
        var versionAttribute = compilation.Assembly.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "AssemblyVersionAttribute");

        if (versionAttribute != null && versionAttribute.ConstructorArguments.Length > 0)
        {
            var versionString = versionAttribute.ConstructorArguments[0].Value?.ToString();
            if (!string.IsNullOrEmpty(versionString))
            {
                // Parse version and return in semver format (Major.Minor.Patch)
                var version = System.Version.Parse(versionString);
                return $"{version.Major}.{version.Minor}.{version.Build}";
            }
        }

        // Try to get version from AssemblyInformationalVersionAttribute
        var infoVersionAttribute = compilation.Assembly.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name == "AssemblyInformationalVersionAttribute");

        if (infoVersionAttribute != null && infoVersionAttribute.ConstructorArguments.Length > 0)
        {
            var versionString = infoVersionAttribute.ConstructorArguments[0].Value?.ToString();
            if (!string.IsNullOrEmpty(versionString))
            {
                // Remove any suffix like "-alpha", "-beta" for version comparison
                var parts = versionString!.Split('-');
                return parts[0];
            }
        }

        // Default fallback
        return "0.1.0";
    }
}
