using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Quark.Generators;

/// <summary>
/// Source generator for Quark streams that creates stream-to-actor mappings.
/// Detects classes with [QuarkStream] attributes and generates registration code.
/// </summary>
[Generator]
public class StreamSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // Find all classes with the QuarkStream attribute
        var streamClasses = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (s, _) => IsSyntaxTargetForGeneration(s),
                static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m is not null);

        // Collect all stream classes
        var compilation = context.CompilationProvider.Combine(streamClasses.Collect());

        // Generate code for all stream actors at once
        context.RegisterSourceOutput(compilation,
            static (spc, source) => Execute(source.Left, source.Right!, spc));
    }

    private static bool IsSyntaxTargetForGeneration(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration
               && classDeclaration.AttributeLists.Count > 0;
    }

    private static StreamActorInfo? GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        var streamNamespaces = new List<string>();

        foreach (var attributeList in classDeclaration.AttributeLists)
        foreach (var attribute in attributeList.Attributes)
        {
            var symbolInfo = context.SemanticModel.GetSymbolInfo(attribute);
            if (symbolInfo.Symbol is not IMethodSymbol attributeSymbol)
                continue;

            var attributeType = attributeSymbol.ContainingType;
            var fullName = attributeType.ToDisplayString();

            if (fullName == "Quark.Abstractions.Streaming.QuarkStreamAttribute")
            {
                // Extract the namespace parameter from the attribute
                if (attribute.ArgumentList?.Arguments.Count > 0)
                {
                    var arg = attribute.ArgumentList.Arguments[0];
                    var value = context.SemanticModel.GetConstantValue(arg.Expression);
                    if (value.HasValue && value.Value is string ns)
                    {
                        streamNamespaces.Add(ns);
                    }
                }
            }
        }

        if (streamNamespaces.Count == 0)
            return null;

        var classSymbol = context.SemanticModel.GetDeclaredSymbol(classDeclaration) as INamedTypeSymbol;
        if (classSymbol == null)
            return null;

        // Find the message type from IStreamConsumer<T>
        var streamConsumerInterface = classSymbol.AllInterfaces
            .FirstOrDefault(i => i.Name == "IStreamConsumer" && i.IsGenericType);

        string? messageTypeName = null;
        if (streamConsumerInterface != null && streamConsumerInterface.TypeArguments.Length > 0)
        {
            messageTypeName = streamConsumerInterface.TypeArguments[0].ToDisplayString();
        }

        return new StreamActorInfo(
            classSymbol.Name,
            classSymbol.ToDisplayString(),
            streamNamespaces.ToArray(),
            messageTypeName);
    }

    private static void Execute(
        Compilation compilation,
        ImmutableArray<StreamActorInfo?> streamActors,
        SourceProductionContext context)
    {
        if (streamActors.IsEmpty)
            return;

        var registrations = new StringBuilder();

        foreach (var info in streamActors)
        {
            if (info is null)
                continue;

            foreach (var ns in info.StreamNamespaces)
            {
                if (info.MessageTypeName != null)
                {
                    registrations.AppendLine(
                        $"        StreamRegistry.RegisterImplicitSubscription(\"{ns}\", typeof({info.FullClassName}), typeof({info.MessageTypeName}));");
                }
            }
        }

        if (registrations.Length == 0)
            return;

        // Generate the module initializer for stream registrations
        var moduleInitSource = $$"""
                                 // <auto-generated/>
                                 #nullable enable
                                 using System.Runtime.CompilerServices;
                                 using Quark.Core.Streaming;

                                 namespace Quark.Generated;

                                 /// <summary>
                                 /// Auto-generated stream registration module.
                                 /// </summary>
                                 public static class StreamRegistrationModule
                                 {
                                     [ModuleInitializer]
                                     public static void Initialize()
                                     {
                                 {{registrations}}
                                     }
                                 }
                                 """;

        context.AddSource("StreamRegistrations.g.cs", moduleInitSource);
    }

    private class StreamActorInfo
    {
        public StreamActorInfo(
            string className,
            string fullClassName,
            string[] streamNamespaces,
            string? messageTypeName)
        {
            ClassName = className;
            FullClassName = fullClassName;
            StreamNamespaces = streamNamespaces;
            MessageTypeName = messageTypeName;
        }

        public string ClassName { get; }
        public string FullClassName { get; }
        public string[] StreamNamespaces { get; }
        public string? MessageTypeName { get; }
    }
}
