using Quark.Core.Abstractions.Grains;
using Quark.Core.Abstractions.Hosting;
using Quark.Core.Abstractions.Identity;
using Quark.Persistence.Abstractions;
using Quark.Runtime;
using Quark.Serialization.Abstractions.Buffers;
using Xunit;

namespace Quark.Tests.Unit.Integration;

// ---------------------------------------------------------------------------
// Invokables (hand-written; MethodIds 20–23 to avoid collisions)
// ---------------------------------------------------------------------------

internal readonly struct EagerResource_GetLoadedByIdInvokable : IGrainInvokable<string>
{
    public uint MethodId => 20u;
    public ValueTask<string> Invoke(IGrainBehavior b) => new(((IEagerResourceGrain)b).GetLoadedByIdAsync());
    public void Serialize(ref CodecWriter w) { }
    public string DeserializeResult(ref CodecReader r) => string.Empty;
}

internal readonly struct EagerResource_GetInitCountInvokable : IGrainInvokable<int>
{
    public uint MethodId => 21u;
    public ValueTask<int> Invoke(IGrainBehavior b) => new(((IEagerResourceGrain)b).GetInitCountAsync());
    public void Serialize(ref CodecWriter w) { }
    public int DeserializeResult(ref CodecReader r) => default;
}

internal readonly struct EagerResource_WasValueAvailableInvokable : IGrainInvokable<bool>
{
    public uint MethodId => 22u;
    public ValueTask<bool> Invoke(IGrainBehavior b) => new(((IEagerResourceGrain)b).WasValueAvailableInOnActivateAsync());
    public void Serialize(ref CodecWriter w) { }
    public bool DeserializeResult(ref CodecReader r) => default;
}

internal readonly struct EagerResource_SelfDestructInvokable : IGrainVoidInvokable
{
    public uint MethodId => 23u;
    public ValueTask Invoke(IGrainBehavior b) => new(((IEagerResourceGrain)b).SelfDestructAsync());
    public void Serialize(ref CodecWriter w) { }
}

// ---------------------------------------------------------------------------
// Proxy (hand-written; normally generated by GrainProxyGenerator)
// ---------------------------------------------------------------------------

public sealed class EagerResourceGrainProxy : IEagerResourceGrain
{
    private readonly GrainId _grainId;
    private readonly IGrainCallInvoker _invoker;

    public EagerResourceGrainProxy(GrainId grainId, IGrainCallInvoker invoker)
    {
        _grainId = grainId;
        _invoker = invoker;
    }

    public Task<string> GetLoadedByIdAsync()
        => _invoker.InvokeAsync<EagerResource_GetLoadedByIdInvokable, string>(_grainId, new EagerResource_GetLoadedByIdInvokable()).AsTask();

    public Task<int> GetInitCountAsync()
        => _invoker.InvokeAsync<EagerResource_GetInitCountInvokable, int>(_grainId, new EagerResource_GetInitCountInvokable()).AsTask();

    public Task<bool> WasValueAvailableInOnActivateAsync()
        => _invoker.InvokeAsync<EagerResource_WasValueAvailableInvokable, bool>(_grainId, new EagerResource_WasValueAvailableInvokable()).AsTask();

    public Task SelfDestructAsync()
        => _invoker.InvokeVoidAsync(_grainId, new EagerResource_SelfDestructInvokable()).AsTask();
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

public sealed class EagerMemoryGrainTests : IAsyncLifetime
{
    private EagerMemoryFixture _fixture = null!;

    public Task InitializeAsync()
    {
        _fixture = new EagerMemoryFixture();
        return Task.CompletedTask;
    }

    public Task DisposeAsync() => _fixture.DisposeAsync().AsTask();

    private IEagerResourceGrain GetGrain(string key)
        => _fixture.Client.GetGrain<IEagerResourceGrain>(key);

    // (a) Factory receives a working scoped IServiceProvider and can resolve a registered service.
    [Fact]
    public async Task Factory_Receives_Scoped_ServiceProvider_With_Registered_Services()
    {
        IEagerResourceGrain grain = GetGrain("scoped-sp");
        string loadedById = await grain.GetLoadedByIdAsync();
        Assert.False(string.IsNullOrEmpty(loadedById));
    }

    // (b) Value is populated INSIDE OnActivateAsync.
    [Fact]
    public async Task Value_Is_Available_Inside_OnActivateAsync()
    {
        IEagerResourceGrain grain = GetGrain("on-activate");
        bool available = await grain.WasValueAvailableInOnActivateAsync();
        Assert.True(available);
    }

    // (b) Value is accessible in later grain calls.
    [Fact]
    public async Task Value_Is_Accessible_In_Subsequent_Calls()
    {
        IEagerResourceGrain grain = GetGrain("subsequent-calls");
        int count1 = await grain.GetInitCountAsync();
        int count2 = await grain.GetInitCountAsync();
        Assert.Equal(1, count1);
        Assert.Equal(1, count2);
    }

    // (c) Factory runs exactly once across multiple calls.
    [Fact]
    public async Task Factory_Runs_Exactly_Once_Per_Activation()
    {
        IEagerResourceGrain grain = GetGrain("factory-once");
        await grain.GetInitCountAsync();
        await grain.GetInitCountAsync();
        int count = await grain.GetInitCountAsync();
        Assert.Equal(1, count);
    }

    // (e) Destroy cleanup runs on deactivation.
    [Fact]
    public async Task Deactivation_Invokes_Destroy_Callback()
    {
        IEagerResourceGrain grain = GetGrain("destroy-test");
        await grain.GetInitCountAsync(); // force access after activation

        var grainId = new GrainId(new GrainType("EagerResourceGrain"), "destroy-test");
        _fixture.ActivationTable.TryGetActivation(grainId, out GrainActivation? activation);
        EagerActivationMemoryHolder<EagerResource> holder = activation!.GetOrCreateEagerHolder<EagerResource>();

        await grain.SelfDestructAsync();
        await Task.Delay(300);

        Assert.Equal(1, holder.Value.DestroyCount);
    }

    // Deactivation should not throw when the grain was activated but SelfDestruct is the first call.
    [Fact]
    public async Task Deactivation_Does_Not_Throw()
    {
        IEagerResourceGrain grain = GetGrain("no-throw-test");
        await grain.SelfDestructAsync();
        await Task.Delay(200);
    }
}
