using Xunit;

namespace Quark.Tests.Unit.Integration;

// ---------------------------------------------------------------------------
// 1. Define the grain interface (Orleans-compatible: IGrainWithStringKey)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 2. Implement the grain
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 3. Method invoker (normally generated by Quark.CodeGenerator)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 4. Proxy (normally generated by Quark.CodeGenerator)
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 5. Test fixture that directly wires DI without IHost
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// 6. End-to-end integration tests
// ---------------------------------------------------------------------------

public sealed class GrainCallIntegrationTests : IAsyncLifetime
{
    private GrainCallFixture _fixture = null!;

    public Task InitializeAsync()
    {
        _fixture = new GrainCallFixture();
        return Task.CompletedTask;
    }

    public Task DisposeAsync()
    {
        return _fixture.DisposeAsync().AsTask();
    }

    private ICounterGrain GetCounter(string key)
    {
        return _fixture.Client.GetGrain<ICounterGrain>(key);
    }

    [Fact]
    public async Task GetGrain_ReturnsProxy_WithCorrectInterface()
    {
        ICounterGrain grain = GetCounter("test-grain");
        Assert.NotNull(grain);
        Assert.IsAssignableFrom<ICounterGrain>(grain);
    }

    [Fact]
    public async Task IncrementAsync_IncrementsCounter()
    {
        ICounterGrain grain = GetCounter("counter-1");
        long result = await grain.IncrementAsync();
        Assert.Equal(1L, result);
    }

    [Fact]
    public async Task MultipleIncrements_SequentialExecution()
    {
        ICounterGrain grain = GetCounter("counter-seq");
        long v1 = await grain.IncrementAsync();
        long v2 = await grain.IncrementAsync();
        long v3 = await grain.IncrementAsync();
        Assert.Equal(1L, v1);
        Assert.Equal(2L, v2);
        Assert.Equal(3L, v3);
    }

    [Fact]
    public async Task GetValue_SameKey_ReturnsSameActivation()
    {
        ICounterGrain grain1 = GetCounter("shared-grain");
        ICounterGrain grain2 = GetCounter("shared-grain");
        await grain1.IncrementAsync();
        await grain1.IncrementAsync();
        Assert.Equal(2L, await grain2.GetValueAsync());
    }

    [Fact]
    public async Task ResetAsync_ResetsCounterToZero()
    {
        ICounterGrain grain = GetCounter("reset-grain");
        await grain.IncrementAsync();
        await grain.IncrementAsync();
        await grain.ResetAsync();
        Assert.Equal(0L, await grain.GetValueAsync());
    }

    [Fact]
    public async Task DifferentKeys_IndependentActivations()
    {
        ICounterGrain grainA = GetCounter("key-a");
        ICounterGrain grainB = GetCounter("key-b");
        await grainA.IncrementAsync();
        await grainA.IncrementAsync();
        await grainB.IncrementAsync();
        Assert.Equal(2L, await grainA.GetValueAsync());
        Assert.Equal(1L, await grainB.GetValueAsync());
    }

    [Fact]
    public async Task ConcurrentCalls_SameGrain_AreSerialized()
    {
        ICounterGrain grain = GetCounter("concurrent-grain");
        var tasks = Enumerable.Range(0, 20)
            .Select(_ => grain.IncrementAsync())
            .ToList();
        long[] results = await Task.WhenAll(tasks);
        Assert.Equal(20L, await grain.GetValueAsync());
        Assert.Equal(
            Enumerable.Range(1, 20).Select(i => (long)i).OrderBy(x => x),
            results.OrderBy(x => x));
    }

    [Fact]
    public async Task GetValue_BeforeAnyCall_ReturnsZero()
    {
        ICounterGrain grain = GetCounter("fresh-grain");
        Assert.Equal(0L, await grain.GetValueAsync());
    }
}
