// Copyright (c) Quark Framework. All rights reserved.

namespace Quark.Abstractions.Streaming;

/// <summary>
/// AOT-safe dispatcher interface for invoking stream consumer methods.
/// Generated by StreamSourceGenerator to eliminate reflection.
/// </summary>
public interface IStreamConsumerDispatcher
{
    /// <summary>
    /// Gets the actor type that this dispatcher handles.
    /// </summary>
    Type ActorType { get; }

    /// <summary>
    /// Gets the message type that this dispatcher handles.
    /// </summary>
    Type MessageType { get; }

    /// <summary>
    /// Activates an actor and notifies it of a stream message.
    /// </summary>
    /// <param name="actorFactory">The actor factory to use for actor creation.</param>
    /// <param name="actorId">The actor ID.</param>
    /// <param name="message">The message to deliver. Can be null for nullable message types.</param>
    /// <param name="streamId">The stream identifier.</param>
    /// <param name="cancellationToken">A cancellation token.</param>
    /// <returns>A task representing the asynchronous operation.</returns>
    Task ActivateAndNotifyAsync(
        IActorFactory actorFactory,
        string actorId,
        object? message,
        StreamId streamId,
        CancellationToken cancellationToken);
}
